version: '3.5'
services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        volumes:
            - "./public:/app"
        ports:
            - "${GATEWAY_PORT}:80"
        networks:
            - ychanter
        restart: "unless-stopped"

networks:
    ychanter:
        name: ychanter-network
        driver: bridge
